name: flutter_lib
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  package_b:
    path: ../package_b

  package_a:
    path: ../package_a

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
