targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - xzvcxc/**.dart
        options:
          compiler: dart2js
        dev_options:
          dart2js_args:
            - --no-minify
        release_options:
          dart2js_args:
            --O0
