name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  built_value: ^8.4.1
  flutter:
    sdk: flutter

  package_a:
    path: ../package_a

  flutter_lib:
    path: ../flutter_lib

  cupertino_icons: ^1.0.5

dev_dependencies:
  build_runner: ^2.3.0
  built_value_generator: ^8.4.1
  build_web_compilers: ^3.2.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
